steps:
  earthly:
    image: earthly/earthly:v0.8.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - earthly bootstrap
      - earthly --ci -P +tests
      - >
        earthly --ci -P +run-all
        --AOC_CONTACT_INFO=$AOC_CONTACT_INFO
        --AOC_SESSION=$AOC_SESSION
    secrets:
      - aoc_contact_info
      - aoc_session
