on:
  push:
  pull_request:

jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v6
      - name: Setup rust toolchain
        uses: https://github.com/dtolnay/rust-toolchain@stable
      - name: Install cargo-nextest
        uses: https://github.com/baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
          locked: true
      - name: Test
        run: |
          cargo nextest run
