[package]
name = "aoc-2023-12"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-timing = { version = "0.1.0", path = "../../../crates/timing" }
env_logger = "0.11.2"
itertools = "0.12.1"
rayon = "1.9.0"
