[package]
name = "aoc-2023-12"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-timing = { workspace = true }
env_logger = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }
