[package]
name = "aoc-2023-12"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-timing = { version = "0.1.0", path = "../../../crates/timing" }
env_logger = "0.10.1"
itertools = "0.12.0"
rayon = "1.8.0"
